import type {
  Workspace,
  Project,
  Task,
  Member,
  DashboardStat,
  WeeklyProgressPoint,
} from "@/types/app";

export const members: Member[] = [
  {
    id: "m1",
    name: "Ava Stone",
    initials: "AS",
    color: "bg-indigo-500",
    role: "Product Lead",
    status: "online",
  },
  {
    id: "m2",
    name: "Mason Park",
    initials: "MP",
    color: "bg-cyan-500",
    role: "Frontend Engineer",
    status: "online",
  },
  {
    id: "m3",
    name: "Lina Kim",
    initials: "LK",
    color: "bg-violet-500",
    role: "Designer",
    status: "away",
  },
];

export const dashboardStats: DashboardStat[] = [
  {
    id: "workspaces",
    label: "Active Workspaces",
    value: "8",
    change: "+2",
    trend: "up",
    hint: "this week",
  },
  {
    id: "assigned",
    label: "Tasks Assigned",
    value: "24",
    change: "+5",
    trend: "up",
    hint: "pending tasks",
  },
  {
    id: "due",
    label: "Tasks Due Today",
    value: "6",
    change: "-2",
    trend: "down",
    hint: "from yesterday",
  },
  {
    id: "activity",
    label: "Team Activity",
    value: "156",
    change: "+23%",
    trend: "up",
    hint: "actions this week",
  },
];

export const weeklyProgress: WeeklyProgressPoint[] = [
  { day: "Mon", value: 8, focus: "Tasks completed" },
  { day: "Tue", value: 14, focus: "Tasks completed" },
  { day: "Wed", value: 11, focus: "Tasks completed" },
  { day: "Thu", value: 18, focus: "Tasks completed" },
  { day: "Fri", value: 15, focus: "Tasks completed" },
  { day: "Sat", value: 9, focus: "Tasks completed" },
  { day: "Sun", value: 5, focus: "Tasks completed" },
];

export const workspaces: Workspace[] = [
  {
    id: "w1",
    name: "Design Team",
    slug: "design-team",
    description: "UI/UX design projects",
    icon: "palette",
    color: "bg-indigo-500",
    projectsCount: 8,
    membersCount: 6,
    updatedAt: "2 hours ago",
    isFavorite: true,
    health: "On Track",
    members,
  },
  {
    id: "w2",
    name: "Development",
    slug: "development",
    description: "Frontend and backend development",
    icon: "layers",
    color: "bg-cyan-500",
    projectsCount: 12,
    membersCount: 9,
    updatedAt: "30 min ago",
    health: "On Track",
    members,
  },
  {
    id: "w3",
    name: "Marketing",
    slug: "marketing",
    description: "Campaigns and content creation",
    icon: "sparkles",
    color: "bg-amber-400",
    projectsCount: 5,
    membersCount: 4,
    updatedAt: "1 day ago",
    health: "Watch",
    members,
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Website Redesign",
    description: "Complete homepage and landing page redesign",
    status: "In Progress",
    priority: "High",
    dueDate: "Mar 15",
    taskCount: 12,
    commentCount: 8,
    attachmentCount: 3,
    workspaceId: "w1",
    workspaceName: "Design Team",
    progress: 65,
    members,
  },
  {
    id: "p2",
    name: "Mobile App v2",
    description: "New features and UI improvements",
    status: "In Review",
    priority: "High",
    dueDate: "Mar 20",
    taskCount: 8,
    commentCount: 5,
    attachmentCount: 2,
    workspaceId: "w2",
    workspaceName: "Development",
    progress: 90,
    members,
  },
  {
    id: "p3",
    name: "Marketing Campaign",
    description: "Spring campaign launch",
    status: "Planning",
    priority: "Medium",
    dueDate: "Apr 1",
    taskCount: 4,
    commentCount: 1,
    attachmentCount: 1,
    workspaceId: "w3",
    workspaceName: "Marketing",
    progress: 25,
    members,
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Design homepage hero section",
    description: "Create compelling hero with animation",
    status: "In Progress",
    priority: "High",
    dueDate: "Today",
    projectId: "p1",
    projectName: "Website Redesign",
    completedSubtasks: 2,
    totalSubtasks: 4,
    commentsCount: 5,
    attachmentsCount: 2,
    assignee: members[0],
  },
  {
    id: "t2",
    title: "Implement authentication flow",
    description: "Add login, register, reset password",
    status: "To Do",
    priority: "High",
    dueDate: "Tomorrow",
    projectId: "p2",
    projectName: "Mobile App v2",
    completedSubtasks: 1,
    totalSubtasks: 3,
    commentsCount: 3,
    attachmentsCount: 1,
    assignee: members[1],
  },
];
